### PR TITLE
Add support for BSD operating systems

### PR DESCRIPTION
**Pull request by yonas**

### CODE REVIEW

**Comment by milesj** [comment]
@yonas Thanks! I'm assuming the entire thing compiles locally now yeah?

With that being said, this will only fix local dev. We don't release to BSD targets yet.

**Comment by yonas** [comment]
> Thanks! I'm assuming the entire thing compiles locally now yeah?

Yes.

> With that being said, this will only fix local dev. We don't release to BSD targets yet.

That's fine. What's holding you back?

**Comment by milesj** [comment]
@yonas Just have to setup all the infra. I'll look into it this weekend and see if I can get it into the release on monday.

**Comment by milesj** [comment]
We extracted proto out into another repo, so I copied over your changes https://github.com/moonrepo/proto/pull/4

**Pull request closed without merging**
