### PR TITLE
internal: Migrate to `AsRef`.

### PR DESCRIPTION
**Pull request by milesj**
All of our shared code/utils should be using `AsRef`, so this starts that initial process.

### CODE REVIEW

**Comment by ofek** [comment]
Hey! What's the benefit of this?

**Comment by milesj** [comment]
@ofek It allows you to pass `String` and `&str` to an argument.

**Comment by ofek** [comment]
Oh and passing `String` would then not be a move?

**Comment by milesj** [comment]
@ofek It unfortunately does not, but allows all of these patterns to "just work".

```
test("foo");
test(String::from("bar"));
test(&baz);
```

**Comment by ofek** [comment]
Got it, thank you!!!

**Pull request merged**
