### PR TITLE
feat: Add spinners to `moon setup` and `moon teardown`.

### PR DESCRIPTION
**Pull request by G3root**
fixes: #12

### CODE REVIEW

**Comment by milesj** [comment]
@G3root Awesome stuff. Easier than expected.

For the PR to pass, can you run `yarn version:bump:bin patch` and push the changes.

**Comment by G3root** [comment]
> @G3root Awesome stuff. Easier than expected.
> 
> For the PR to pass, can you run `yarn version:bump:bin patch` and push the changes.

Done

**Comment by milesj** [comment]
@G3root Ah, I wasn't expecting you to rebase against the develop branch. You'll need to fix the conflicts now :/

**Comment by G3root** [comment]
i'm new to these type of things . is it resolved ?

**Comment by milesj** [comment]
Thanks! I'll fix these minor issues in the development branch.

**Pull request merged**
